In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('newUnion.csv')

In [8]:
companies = set(df['Company Name'])

In [12]:
ndf = pd.DataFrame(index=range(0,len(companies)))

In [14]:
ndf

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[172 rows x 0 columns]

In [17]:
ndf['companies'] = list(companies)

In [19]:
ndf.to_csv('cSet.csv')

In [20]:
oldList = pd.read_csv('oldList.csv')

In [21]:
oldList

corporation
0                      Twitter
1                     Facebook
2   Sears Holdings Corporation
3        Wells Fargo & Company
4                      Comcast
..                         ...
65         Publix Supermarkets
66                     Samsung
67                      Nestle
68                     Wegmans
69                 Chick-fil-A

[70 rows x 1 columns]

In [22]:
newList = pd.read_csv('newList.csv')

In [23]:
newList

companies
0     3M Company
1         Adidas
2         Airbnb
3           Aldi
4       Allstate
..           ...
137  Wells Fargo
138      Wendy's
139     Wish.com
140  Yum! Brands
141   Zoom Video

[142 rows x 1 columns]

In [35]:
len(newData)

51

In [26]:
len(new)

142

In [39]:
newData = []
new = newList['companies'].to_list()
old = oldList['corporation'].to_list()
for i in new:
    if i not in old:
        newData.append(i)
newData

['3M Company',
 'Airbnb',
 'Aldi',
 'Allstate',
 'Amazon',
 'American Airlines',
 'Berkshire Hathaway',
 'Boeing',
 'Burger King',
 'Capital One',
 'Charter',
 'Chewy',
 'Coca-Cola',
 'CVS',
 'Dell',
 "Dick's Sporting Goods",
 'Dish',
 "Domino's Pizza",
 'DoorDash',
 'Electronic Arts',
 'FedEx Corporation',
 'Fiat Chrysler',
 'Fidelity',
 'Ford',
 'Forever 21',
 'GameStop',
 'General Mills',
 'Goldman Sachs',
 'Goya',
 'Grubhub Inc.',
 'Honda',
 'Honeywell International',
 'HP',
 'Huawei Technologies',
 'Hulu',
 'Hyundai',
 'IBM',
 'In-n-Out Burger',
 'Instacart',
 'JPMorgan Chase',
 'Juul Labs',
 'Kaiser Permanente',
 'Kraft Heinz',
 'Kroger',
 'L.L. Bean',
 'LG',
 'Mastercard',
 'MLB',
 'Moderna',
 'Coors',
 'Monsanto',
 'NBA',
 'NFL',
 'Nintendo',
 "Papa John's",
 'Patagonia',
 'Paypal',
 'Peloton',
 'Pfizer',
 'PG&E',
 'Phillip Morris',
 'Procter & Gamble',
 'Progressive',
 'Publix',
 'Reddit',
 'REI',
 'Robinhood',
 'Shell',
 'Sears',
 'Southwest Airlines',
 'SpaceX',
 'Spirit Air

In [36]:
if 'Facebook' in old:
    print(True)

True


In [37]:
if 'Facebook' in new:
    print(True)

True


In [38]:
if 'Facebook' in newData:
    print(True)

True


In [40]:
len(newData)

91

In [41]:
newData

['3M Company',
 'Airbnb',
 'Aldi',
 'Allstate',
 'Amazon',
 'American Airlines',
 'Berkshire Hathaway',
 'Boeing',
 'Burger King',
 'Capital One',
 'Charter',
 'Chewy',
 'Coca-Cola',
 'CVS',
 'Dell',
 "Dick's Sporting Goods",
 'Dish',
 "Domino's Pizza",
 'DoorDash',
 'Electronic Arts',
 'FedEx Corporation',
 'Fiat Chrysler',
 'Fidelity',
 'Ford',
 'Forever 21',
 'GameStop',
 'General Mills',
 'Goldman Sachs',
 'Goya',
 'Grubhub Inc.',
 'Honda',
 'Honeywell International',
 'HP',
 'Huawei Technologies',
 'Hulu',
 'Hyundai',
 'IBM',
 'In-n-Out Burger',
 'Instacart',
 'JPMorgan Chase',
 'Juul Labs',
 'Kaiser Permanente',
 'Kraft Heinz',
 'Kroger',
 'L.L. Bean',
 'LG',
 'Mastercard',
 'MLB',
 'Moderna',
 'Coors',
 'Monsanto',
 'NBA',
 'NFL',
 'Nintendo',
 "Papa John's",
 'Patagonia',
 'Paypal',
 'Peloton',
 'Pfizer',
 'PG&E',
 'Phillip Morris',
 'Procter & Gamble',
 'Progressive',
 'Publix',
 'Reddit',
 'REI',
 'Robinhood',
 'Shell',
 'Sears',
 'Southwest Airlines',
 'SpaceX',
 'Spirit Air

In [42]:
ct = pd.read_csv('corp_trends.csv')

In [43]:
ct

Unnamed: 0  Twitter  Facebook  Sears Holdings Corporation  \
0          AL    58.60     48.00                        2.80   
1          AZ    67.67     36.67                       35.00   
2          AR    56.25     42.00                       11.00   
3          CA    71.92     33.92                        4.92   
4          CO    58.67     37.67                        0.00   
5          CT    79.00     31.00                        0.00   
6          DE      NaN       NaN                         NaN   
7          FL    62.80     36.30                        7.50   
8          GA    59.00     45.14                        0.86   
9          ID    48.00     39.67                        0.00   
10         IL    65.14     46.43                        6.00   
11         IN    66.67     40.17                        1.50   
12         IA    66.57     47.71                        0.00   
13         KS    60.67     43.33                        0.00   
14         KY    66.50     44.50                        0.00   
15         LA    56.57     41.86                        2.14   
16         ME    55.33     58.67                        0.00   
17         MD    83.67     35.00                       12.00   
18         MA    82.00     34.00                        2.00   
19         MI    61.86     46.71                        2.14   
20         MN    68.75     40.50                        3.75   
21         MS    54.17     48.33                        0.00   
22         MO    59.44     45.44                        0.89   
23         MT    54.00     49.17                        0.00   
24         NE    61.50     43.50                        0.00   
25         NV    71.50     31.50                        0.00   
26         NH    90.00     30.00                        6.00   
27         NJ      NaN       NaN                         NaN   
28         NM    60.00     43.00                        0.00   
29         NY    71.90     43.60                       15.60   
30         NC    62.00     41.33                        5.50   
31         ND    59.00     45.00                        0.00   
32         OH    70.22     46.22                        1.11   
33         OK    55.75     40.75                        0.00   
34         OR    65.75     38.75                        3.50   
35         PA    74.17     42.17                       10.33   
36         RI    79.00     35.00                        0.00   
37         SC    59.75     43.50                       10.50   
38         SD    63.00     49.00                        0.00   
39         TN    62.17     46.50                        0.00   
40         TX    59.05     38.53                        1.53   
41         UT    58.00     29.00                        0.00   
42         VT    65.00     44.00                       34.00   
43         VA    75.00     39.80                       11.00   
44         WA    67.00     39.00                        5.67   
45         WV    62.80     54.20                        0.00   
46         WI    61.67     41.83                        7.50   
47         WY    43.50     50.50                        0.00   
48         DC   100.00     27.00                       19.00   

    Wells Fargo & Company  Comcast  McDonald's  United Airlines  Target  \
0                     0.0    15.00       64.20            13.40   42.80   
1                     0.0    10.33       61.33            24.67   51.33   
2                     0.0    13.25       70.75            16.00   35.25   
3                     0.0    21.00       54.00            36.25   59.17   
4                     0.0    34.33       54.00            68.33   46.00   
5                     0.0    47.00       56.00            23.00   48.00   
6                     NaN      NaN         NaN              NaN     NaN   
7                     0.0    41.90       56.10            25.90   46.60   
8                     0.0    27.29       60.29            11.29   38.00   
9                     0.0     2.67       54.00      

In [50]:
(ct.dropna())['Comcast'].describe()

count    47.000000
mean     23.214255
std      20.442245
min       1.500000
25%       5.000000
50%      15.000000
75%      34.500000
max      78.000000
Name: Comcast, dtype: float64

In [51]:
from sklearn.preprocessing import OrdinalEncoder

In [52]:
data = ct.dropna().drop(['Unnamed: 0'],axis=1)
data

Twitter  Facebook  Sears Holdings Corporation  Wells Fargo & Company  \
0     58.60     48.00                        2.80                    0.0   
1     67.67     36.67                       35.00                    0.0   
2     56.25     42.00                       11.00                    0.0   
3     71.92     33.92                        4.92                    0.0   
4     58.67     37.67                        0.00                    0.0   
5     79.00     31.00                        0.00                    0.0   
7     62.80     36.30                        7.50                    0.0   
8     59.00     45.14                        0.86                    0.0   
9     48.00     39.67                        0.00                    0.0   
10    65.14     46.43                        6.00                    0.0   
11    66.67     40.17                        1.50                    0.0   
12    66.57     47.71                        0.00                    0.0   
13    60.67     43.33                        0.00                    0.0   
14    66.50     44.50                        0.00                    0.0   
15    56.57     41.86                        2.14                    0.0   
16    55.33     58.67                        0.00                    0.0   
17    83.67     35.00                       12.00                    0.0   
18    82.00     34.00                        2.00                    0.0   
19    61.86     46.71                        2.14                    0.0   
20    68.75     40.50                        3.75                    0.0   
21    54.17     48.33                        0.00                    0.0   
22    59.44     45.44                        0.89                    0.0   
23    54.00     49.17                        0.00                    0.0   
24    61.50     43.50                        0.00                    0.0   
25    71.50     31.50                        0.00                    0.0   
26    90.00     30.00                        6.00                    0.0   
28    60.00     43.00                        0.00                    0.0   
29    71.90     43.60                       15.60                   10.0   
30    62.00     41.33                        5.50                    0.0   
31    59.00     45.00                        0.00                    0.0   
32    70.22     46.22                        1.11                    0.0   
33    55.75     40.75                        0.00                    0.0   
34    65.75     38.75                        3.50                    0.0   
35    74.17     42.17                       10.33                    0.0   
36    79.00     35.00                        0.00                    0.0   
37    59.75     43.50                       10.50                    0.0   
38    63.00     49.00                        0.00                    0.0   
39    62.17     46.50                        0.00                    0.0   
40    59.05     38.53                        1.53                    0.0   
41    58.00     29.00                        0.00                    0.0   
42    65.00     44.00                       34.00                    0.0   
43    75.00     39.80                       11.00                    0.0   
44    67.00     39.00                        5.67                    0.0   
45    62.80     54.20                        0.00                    0.0   
46    61.67     41.83                        7.50                    0.0   
47    43.50     50.50                        0.00                    0.0   
48   100.00     27.00                       19.00                    0.0   

    Comcast  McDonald's  United Airlines  Target  Bank of America  \
0     15.00       64.20            13.40   42.80            15.00   
1     10.33       61.33            24.67   51.33            53.33   
2     13.25       70.75            16.00   35.25            24.00   
3     21.00       54.00            36.25   59.17            69.00   
4     34.3

In [53]:
# data = ct.dropna().drop(['Unnamed: 0'],axis=1)
encoder = OrdinalEncoder()
# transform data
result = encoder.fit_transform(data)
print(result)

[[ 9. 38.  8. ...  2.  0. 41.]
 [31.  9. 23. ... 10.  0. 21.]
 [ 6. 22. 18. ... 33.  0. 29.]
 ...
 [18. 20. 15. ... 30.  0.  6.]
 [ 0. 42.  0. ... 15.  0. 20.]
 [43.  0. 21. ... 29.  7. 35.]]


In [54]:
result

array([[ 9., 38.,  8., ...,  2.,  0., 41.],
       [31.,  9., 23., ..., 10.,  0., 21.],
       [ 6., 22., 18., ..., 33.,  0., 29.],
       ...,
       [18., 20., 15., ..., 30.,  0.,  6.],
       [ 0., 42.,  0., ..., 15.,  0., 20.],
       [43.,  0., 21., ..., 29.,  7., 35.]])